services:
  application:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: application
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
  db:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DATABASE: cadastro_livros
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    networks:
      - laravel_app
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/root/redis
      - /docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=cadastro_livros
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
networks:
  laravel_app:
    driver: bridge
